# name: Update version and upload bundle.js to S3 to x.y.z.js & latest.js

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Update version
#         uses: appleboy/semver-action@v0.5.0
#         with:
#           version: 'auto'
#           prefix: 'v'

#       - name: Upload latest.js to S3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --delete --exclude '*' --include 'hello_world.rb' s3://a1-community-widget/latest.js
#         env:
#           AWS_S3_BUCKET: a1-community-widget
#           AWS_REGION: us-east-1
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}